version: '2'
services:
    cfp-app:
        image: cfp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cfp-mysql:3306/cfp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cfp-mysql:
        extends:
            file: mysql.yml
            service: cfp-mysql
